### ISSUE TITLE
README.md example is incorrect

### ISSUE THREAD

**Issue by jmgnc** [erezsh/plyplus#47]
The calc example does not work. You need to wrap "calc.g" w/ an open.  If you don't, you get:
```>>> import plyplus
>>> plyplus.Grammar("calc.g").parse("(1 + 2) * -3")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jmg/work/scobreak/p/lib/python2.7/site-packages/plyplus/plyplus.py", line 560, in __init__
    self._grammar = self._create_grammar(grammar, source, tab_filename, options)
  File "/Users/jmg/work/scobreak/p/lib/python2.7/site-packages/plyplus/plyplus.py", line 565, in _create_grammar
    grammar_tree = grammar_parser.parse(grammar)
  File "/Users/jmg/work/scobreak/p/lib/python2.7/site-packages/plyplus/grammar_parser.py", line 156, in parse
    return _parser.parse(text, lexer=lexer, debug=debug)
  File "/Users/jmg/work/scobreak/p/lib/python2.7/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/jmg/work/scobreak/p/lib/python2.7/site-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/Users/jmg/work/scobreak/p/lib/python2.7/site-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/Users/jmg/work/scobreak/p/lib/python2.7/site-packages/plyplus/grammar_lexer.py", line 57, in t_error
    raise Exception("Illegal character in grammar: %r in %r" % (t.value[0], t.value[:10] ))
Exception: Illegal character in grammar: '.' in '.g'
```

if instead you do:
```>>> plyplus.Grammar(open("calc.g")).parse("(1 + 2) * -3")
start(mul(add(number(u'1'), add_symbol(u'+'), number(u'2')), mul_symbol(u'*'), neg(number(u'3'))))
```

you can see that it works.

**Comment by erezsh** [comment]
Thanks, I'll fix it.

Also, I suggest you check out my new parsing library: https://github.com/erezsh/lark
It's a lot better!

**Comment by erezsh** [comment]
Should be okay now.
